version: '3.2'

services:
  db:
    image: mariadb:10.11
    # image: mysql:8.0.16
    restart: always
    ports:
      - '${MYSQL_PORT}:3306' # expose ports - HOST:CONTAINER
    # expose:
    #     - '3306' # Expose ports without publishing them to the host machine
    volumes:
      - './data/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:6.4.3-fpm-alpine
    restart: always
    links:
      - db
    expose:
      - '9000' # Expose ports without publishing them to the host machine
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:1.25.4-alpine
    restart: always
    links:
      - wordpress
    ports:
      - '${NGINX_PORT}:80' # expose ports - HOST:CONTAINER
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html
